# Generated by Django 5.0.1 on 2024-01-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='document_image',
            field=models.FileField(null=True, upload_to='tenant_documents/'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='document_proofs',
            field=models.CharField(choices=[('aadhar', 'Aadhar Card'), ('pancard', 'PAN Card'), ('passport', 'Passport')], max_length=10),
        ),
    ]
