# Generated by Django 5.0.1 on 2024-01-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_tenant_document_image_alter_tenant_document_proofs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='tenant',
            new_name='tenant_id',
        ),
    ]
